[EHT-550] Feature/apt installation
encapsulate-xyz/mina-ansible pull request #1
Opened 2024-12-13 11:10 UTC by kowshikvajrala

2024-12-13 12:55 UTC, aditya-manit requested changes

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/defaults/main.yml
> +node_public_key_path: "{{ node_key_dir }}/{{ node_public_key_file_name }}"
do we need this ?

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/tasks/install_binary.yml
> +    uris: http://packages.o1test.net
lets put it in source_url and use it here

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/defaults/main.yml
> +node_environment_general_file_path: "{{ node_env_dir }}/{{ node_environment_general_file_name }}"
node_environment_general_file_path is not being used

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/defaults/main.yml
> +node_environment_general_file_path: "{{ node_env_dir }}/{{ node_environment_general_file_name }}"
I think you have moved everything to system service already

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/templates/mainnet/systemd.service.j2
> +  --block-producer-key {{ node_private_key_path }} \
--block-producer-key is DEPRECATED use env variable

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/templates/mainnet/systemd.service.j2
> +  --log-level Info --file-log-level Debug \
2024-12-13 11:10:49 UTC [Error] libp2p_helper: failed to set log level debug for routing/record: error: No such logger


check this once, are both of them required ? if yes then set both to info, but I think only should be required

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/templates/mainnet/systemd.service.j2
> +  --peer-list-url "https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt" \
lets fetch this from group vars

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/templates/mainnet/systemd.service.j2
> +  --uptime-url "https://uptime-backend.minaprotocol.com/v1/submit"
lets fetch this from group vars

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/templates/testnet/systemd.service.j2
> +ExecStart={{ node_bin_dir }}/{{ service_identifier }} daemon --config-directory {{ node_config_dir }} \
make the same changes here as well

2024-12-13 12:55 UTC, aditya-manit commented on group_vars/all.yml
> +      external_port: 8302
do we need 8303 anywere too ?

2024-12-13 12:55 UTC, aditya-manit commented on tasks/create_user_and_directories.yml
> +    mode: "0700"
does it not start without 700 ?

2024-12-13 12:55 UTC, aditya-manit commented on roles/node/templates/testnet/systemd.service.j2
> +  --peer-list-url "https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt" \
mainnet_seeds.txt in testnet ?

2024-12-13 16:35 UTC, kowshikvajrala commented on roles/node/templates/mainnet/systemd.service.j2
> +  --block-producer-key {{ node_private_key_path }} \
"monitor.ml.Error",
    [ "Base58_check.Invalid_base58_character(\"Private key\")" ],
    
    when i use the env varibale it's throwing this error

2024-12-13 17:01 UTC, kowshikvajrala commented on roles/node/templates/mainnet/systemd.service.j2
> +  --log-level Info --file-log-level Debug \
That error is present even if it's not set

2024-12-14 06:23 UTC, aditya-manit approved these changes

2024-12-14 06:23 UTC, merged